---
- name: Local Deployment Environment Setup Helper (Ubuntu 18.04)
  hosts: localhost
  connection: local
  become_user: root
  become_method: sudo
  become: true
  gather_facts: true

  vars:
    target_user: /var/lib/jenkins/

  roles:
    - role: os/base_tools
    - role: os/nodejs
    - role: apps/awscli
    - role: apps/docker
    - role: sharp/nodeenv-sls
